In [1]:
print("Hello world!")

Hello world!


In [2]:
num=256
string="yuri_ebihara"
print(f"num={num}, type(num)={type(num)}")
print(f"string={string}, type(string)={type(string)}")

num=256, type(num)=<class 'int'>
string=yuri_ebihara, type(string)=<class 'str'>


In [1]:
price1=[120,180]
price2=[300,150]
all=[price1,price2]
all

[[120, 180], [300, 150]]

In [2]:
len(price1)

2

In [3]:
len(all)

2

In [4]:
all[0][1]

180

In [5]:
price=[]
price.append(price1)
price.append(price2)
price

[[120, 180], [300, 150]]

In [6]:
import numpy as np
price1=np.array([256,512])
price2=np.array([[3.14,25],[-128,0]])
price1
price2

array([[   3.14,   25.  ],
       [-128.  ,    0.  ]])

In [7]:
price1

array([256, 512])

In [8]:
price1.dtype

dtype('int64')

In [9]:
price2.dtype

dtype('float64')

In [10]:
price1.shape

(2,)

In [11]:
price1=np.array([[256, 512]])
price1

array([[256, 512]])

In [12]:
price1.shape

(1, 2)

In [13]:
price2.shape

(2, 2)